// Re-export all shared types from the parent project's schema
// This avoids complex path resolution issues with Metro/TypeScript
export type {
  Family,
  User,
  Profile,
  Child,
  Event,
  Activity,
  Friend,
  SocialEvent,
  ReadingListItem,
  SchoolTask,
  HandoverNote,
  Expense,
  Message,
  Document,
  OsloEvent,
  InsertUser,
  InsertChild,
  InsertEvent,
  InsertActivity,
  InsertFriend,
  InsertSocialEvent,
  InsertReadingListItem,
  InsertSchoolTask,
  InsertHandoverNote,
  InsertExpense,
  InsertMessage,
  InsertDocument,
  // Phase 1: Push Notifications
  DeviceToken,
  NotificationPreferences,
  InsertDeviceToken,
  UpdateNotificationPreferences,
  // Phase 2: PDF Export Engine
  ExportAuditLog,
  CreateExport,
  // Phase 3: Custody Schedule Templates
  CustodySchedule,
  CustodySwapRequest,
  CustodyDay,
  InsertCustodySchedule,
  InsertSwapRequest,
  CustodyTemplateType,
  SwapRequestStatus,
  // Phase 4: Tone Detection
  ToneCheckResult,
  ToneLabel,
  ToneCheckRequest,
  // Phase 5: Attorney/Mediator Portals
  ProfessionalInvite,
  ProfessionalAccess,
  ProfessionalRole,
  CreateProfessionalInvite,
  UpdateProfessionalAccess,
  // Phase 6: Payment Integration
  UpdatePaymentInfo,
} from "../../../shared/schema";

export {
  insertUserSchema,
  loginSchema,
  insertChildSchema,
  insertEventSchema,
  insertActivitySchema,
  insertFriendSchema,
  insertSocialEventSchema,
  insertReadingListSchema,
  insertSchoolTaskSchema,
  insertHandoverNoteSchema,
  insertExpenseSchema,
  insertMessageSchema,
  insertDocumentSchema,
} from "../../../shared/schema";
