// Re-export all shared types from the parent project's schema
// This avoids complex path resolution issues with Metro/TypeScript
export type {
  Family,
  User,
  Profile,
  Child,
  Event,
  Activity,
  Friend,
  SocialEvent,
  ReadingListItem,
  SchoolTask,
  HandoverNote,
  Expense,
  Message,
  Document,
  OsloEvent,
  InsertUser,
  InsertChild,
  InsertEvent,
  InsertActivity,
  InsertFriend,
  InsertSocialEvent,
  InsertReadingListItem,
  InsertSchoolTask,
  InsertHandoverNote,
  InsertExpense,
  InsertMessage,
  InsertDocument,
} from "../../../shared/schema";

export {
  insertUserSchema,
  loginSchema,
  insertChildSchema,
  insertEventSchema,
  insertActivitySchema,
  insertFriendSchema,
  insertSocialEventSchema,
  insertReadingListSchema,
  insertSchoolTaskSchema,
  insertHandoverNoteSchema,
  insertExpenseSchema,
  insertMessageSchema,
  insertDocumentSchema,
} from "../../../shared/schema";
